server:
  port: 8801

spring:
  application:
    name: consumer
  zipkin:
    base-url: http://chainmonitor/
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/