server:
  port: 8770

spring:
  application:
    name: chainmonitor

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  # 关闭自动配置启用所有请求de检测
management:
  metrics:
    web:
      server:
        auto-time-requests: false